// Actions
export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const DIRECTIONAL_TURN = 'DIRECTIONAL_TURN';
export const SOUNDSOURCE_DESELECTED = 'SOUNDSOURCE_DESELECTED';
export const SOUNDSOURCE_DESELECT_ALL = 'SOUNDSOURCE_DESELECT_ALL';
export const SOUNDSOURCE_SELECTED = 'SOUNDSOURCE_SELECTED';
export const SOUNDSOURCE_MOVED_INTERIM = 'SOUNDSOURCE_MOVED_INTERIM';
export const SOUNDSOURCE_MOVED_COMMIT = 'SOUNDSOURCE_MOVED_COMMIT';

export const ANGLE_TURN_SENSITIVITY = 0.05;
export const FONT_FACE = 'Arial';
export const FONT_SIZE = 20;
export const FILENAME_LENGTH = 15;
